export const SERVER_ERROR_CODE = {
  // Auth
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NOT_LOGGED_IN: 'NOT_LOGGED_IN',
  ACCESS_DENIED: 'ACCESS_DENIED',
  MISSING_REFRESH_TOKEN: 'MISSING_REFRESH_TOKEN',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  // 비밀번호재설정·이메일인증 토큰 전용(위 INVALID_REFRESH_TOKEN과 별개 - BE
  // InvalidActionTokenException 참고)
  INVALID_ACTION_TOKEN: 'INVALID_ACTION_TOKEN',
  DUPLICATE_NICKNAME: 'DUPLICATE_NICKNAME',

  // Common
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  // CloudFront/WAF가 앱에 닿기 전에 막은 요청 (403 + 비-JSON HTML 응답)
  EDGE_BLOCKED: 'EDGE_BLOCKED',
} as const;

export type ServerErrorCode = keyof typeof SERVER_ERROR_CODE;
